const Payroll = require('../payroll/model');

const sumBasic = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.l0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.l0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.l0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.l0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.l0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.l0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.l0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.l0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.l0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.l0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.l0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.l0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tBasic: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sBasic: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumOT = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.ai0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.ai0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.ai0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.ai0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.ai0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.ai0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.ai0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.ai0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.ai0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.ai0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.ai0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.ai0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tOT: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sOT: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumAllow = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.bk0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.bk0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.bk0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.bk0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.bk0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.bk0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.bk0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.bk0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.bk0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.bk0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.bk0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.bk0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tAllow: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sAllow: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumOAllow = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.bu0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.bu0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.bu0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.bu0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.bu0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.bu0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.bu0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.bu0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.bu0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.bu0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.bu0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.bu0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tOAllow: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sOAllow: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumPesangon = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.en0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.en0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.en0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.en0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.en0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.en0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.en0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.en0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.en0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.en0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.en0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.en0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tPesangon: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sPesangon: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumThr = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.eq0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.eq0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.eq0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.eq0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.eq0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.eq0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.eq0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.eq0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.eq0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.eq0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.eq0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.eq0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tThr: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sThr: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumOIncome = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.dr0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.dr0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.dr0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.dr0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.dr0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.dr0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.dr0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.dr0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.dr0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.dr0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.dr0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.dr0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tOIncome: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sOIncome: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumAbsent = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.cy0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.cy0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.cy0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.cy0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.cy0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.cy0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.cy0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.cy0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.cy0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.cy0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.cy0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.cy0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tAbsent: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sAbsent: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumODeduction = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.df0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.df0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.df0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.df0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.df0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.df0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.df0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.df0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.df0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.df0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.df0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.df0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tODeduction: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sODeduction: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumICo = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.cn0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.cn0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.cn0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.cn0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.cn0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.cn0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.cn0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.cn0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.cn0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.cn0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.cn0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.cn0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tICo: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sICo: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumIEmp = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.er0', else: 0 } } },
        feb: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.er0', else: 0 } } },
        mar: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.er0', else: 0 } } },
        apr: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.er0', else: 0 } } },
        mei: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.er0', else: 0 } } },
        jun: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.er0', else: 0 } } },
        jul: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.er0', else: 0 } } },
        agu: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.er0', else: 0 } } },
        sep: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.er0', else: 0 } } },
        okt: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.er0', else: 0 } } },
        nov: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.er0', else: 0 } } },
        des: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.er0', else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan: '$jan',
            feb: '$feb',
            mar: '$mar',
            apr: '$apr',
            mei: '$mei',
            jun: '$jun',
            jul: '$jul',
            agu: '$agu',
            sep: '$sep',
            okt: '$okt',
            nov: '$nov',
            des: '$des',
            tIEmp: { $sum: ['$jan', '$feb', '$mar', '$apr', '$mei', '$jun', '$jul', '$agu', '$sep', '$okt', '$nov', '$des'] },
          },
        },
        totJan: { $sum: '$jan' },
        totFeb: { $sum: '$feb' },
        totMar: { $sum: '$mar' },
        totApr: { $sum: '$apr' },
        totMei: { $sum: '$mei' },
        totJun: { $sum: '$jun' },
        totJul: { $sum: '$jul' },
        totAgu: { $sum: '$agu' },
        totSep: { $sum: '$sep' },
        totOkt: { $sum: '$okt' },
        totNov: { $sum: '$nov' },
        totDes: { $sum: '$des' },
      },
    },
    {
      $addFields: {
        sIEmp: { $sum: ['$totJan', '$totFeb', '$totMar', '$totApr', '$totMei', '$totJun', '$totJul', '$totAgu', '$totSep', '$totOkt', '$totNov', '$totDes'] },
      },
    },
  ]);

  return p[0];
};

const sumTax = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        jan1: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: '$employee.es0', else: 0 } } },
        feb1: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: '$employee.es0', else: 0 } } },
        mar1: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: '$employee.es0', else: 0 } } },
        apr1: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: '$employee.es0', else: 0 } } },
        mei1: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: '$employee.es0', else: 0 } } },
        jun1: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: '$employee.es0', else: 0 } } },
        jul1: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: '$employee.es0', else: 0 } } },
        agu1: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: '$employee.es0', else: 0 } } },
        sep1: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: '$employee.es0', else: 0 } } },
        okt1: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: '$employee.es0', else: 0 } } },
        nov1: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: '$employee.es0', else: 0 } } },
        des1: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: '$employee.es0', else: 0 } } },
        jan2: { $sum: { $cond: { if: { $eq: ['$month', 0] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        feb2: { $sum: { $cond: { if: { $eq: ['$month', 1] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        mar2: { $sum: { $cond: { if: { $eq: ['$month', 2] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        apr2: { $sum: { $cond: { if: { $eq: ['$month', 3] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        mei2: { $sum: { $cond: { if: { $eq: ['$month', 4] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        jun2: { $sum: { $cond: { if: { $eq: ['$month', 5] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        jul2: { $sum: { $cond: { if: { $eq: ['$month', 6] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        agu2: { $sum: { $cond: { if: { $eq: ['$month', 7] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        sep2: { $sum: { $cond: { if: { $eq: ['$month', 8] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        okt2: { $sum: { $cond: { if: { $eq: ['$month', 9] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        nov2: { $sum: { $cond: { if: { $eq: ['$month', 10] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
        des2: { $sum: { $cond: { if: { $eq: ['$month', 11] }, then: { $subtract: ['$employee.db0', '$employee.es0'] }, else: 0 } } },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            jan1: '$jan1',
            feb1: '$feb1',
            mar1: '$mar1',
            apr1: '$apr1',
            mei1: '$mei1',
            jun1: '$jun1',
            jul1: '$jul1',
            agu1: '$agu1',
            sep1: '$sep1',
            okt1: '$okt1',
            nov1: '$nov1',
            des1: '$des1',
            jan2: '$jan2',
            feb2: '$feb2',
            mar2: '$mar2',
            apr2: '$apr2',
            mei2: '$mei2',
            jun2: '$jun2',
            jul2: '$jul2',
            agu2: '$agu2',
            sep2: '$sep2',
            okt2: '$okt2',
            nov2: '$nov2',
            des2: '$des2',
            tTax: { $sum: ['$jan1', '$feb1', '$mar1', '$apr1', '$mei1', '$jun1', '$jul1', '$agu1', '$sep1', '$okt1', '$nov1', '$des1', '$jan2', '$feb2', '$mar2', '$apr2', '$mei2', '$jun2', '$jul2', '$agu2', '$sep2', '$okt2', '$nov2', '$des2'] },
          },
        },
        totJan1: { $sum: '$jan1' },
        totFeb1: { $sum: '$feb1' },
        totMar1: { $sum: '$mar1' },
        totApr1: { $sum: '$apr1' },
        totMei1: { $sum: '$mei1' },
        totJun1: { $sum: '$jun1' },
        totJul1: { $sum: '$jul1' },
        totAgu1: { $sum: '$agu1' },
        totSep1: { $sum: '$sep1' },
        totOkt1: { $sum: '$okt1' },
        totNov1: { $sum: '$nov1' },
        totDes1: { $sum: '$des1' },
        totJan2: { $sum: '$jan2' },
        totFeb2: { $sum: '$feb2' },
        totMar2: { $sum: '$mar2' },
        totApr2: { $sum: '$apr2' },
        totMei2: { $sum: '$mei2' },
        totJun2: { $sum: '$jun2' },
        totJul2: { $sum: '$jul2' },
        totAgu2: { $sum: '$agu2' },
        totSep2: { $sum: '$sep2' },
        totOkt2: { $sum: '$okt2' },
        totNov2: { $sum: '$nov2' },
        totDes2: { $sum: '$des2' },
      },
    },
    {
      $addFields: {
        sTax: { $sum: ['$totJan1', '$totFeb1', '$totMar1', '$totApr1', '$totMei1', '$totJun1', '$totJul1', '$totAgu1', '$totSep1', '$totOkt1', '$totNov1', '$totDes1', '$totJan2', '$totFeb2', '$totMar2', '$totApr2', '$totMei2', '$totJun2', '$totJul2', '$totAgu2', '$totSep2', '$totOkt2', '$totNov2', '$totDes2'] },
      },
    },
  ]);

  return p[0];
};

const sumAll = async (id) => {
  const p = await Payroll.aggregate([
    { $match: { year: id } },
    { $unwind: '$employee' },
    {
      $group: {
        _id: {
          e0: '$employee.e0',
        },
        d0: { $first: '$employee.d0' },
        e0: { $first: '$employee.e0' },
        i0: { $last: '$employee.i0' },
        u0: { $last: '$employee.u0' },
        y0: { $last: '$employee.y0' },
        tBasic: { $sum: '$employee.l0' },
        tOT: { $sum: '$employee.ai0' },
        tAllow: { $sum: '$employee.bk0' },
        tOAllow: { $sum: '$employee.bu0' },
        tPesangon: { $sum: '$employee.en0' },
        tThr: { $sum: '$employee.eq0' },
        tOIncome: { $sum: '$employee.dr0' },
        tAbsent: { $sum: '$employee.cy0' },
        tODeduction: { $sum: '$employee.df0' },
        tICo: { $sum: '$employee.cn0' },
        tIEmp: { $sum: '$employee.er0' },
        tTax: { $sum: '$employee.db0' },
      },
    },
    { $sort: { '_id.e0': 1 } },
    {
      $group: {
        _id: 'summary',
        employee: {
          $push: {
            _id: '$e0',
            d0: '$d0',
            e0: '$e0',
            i0: '$i0',
            u0: '$u0',
            y0: '$y0',
            tBasic: '$tBasic',
            tOT: '$tOT',
            tAllow: '$tAllow',
            tOAllow: '$tOAllow',
            tPesangon: '$tPesangon',
            tThr: '$tThr',
            tOIncome: '$tOIncome',
            tAbsent: '$tAbsent',
            tODeduction: '$tODeduction',
            tICo: '$tICo',
            tIEmp: '$tIEmp',
            tTax: '$tTax',
          },
        },
        sBasic: { $sum: '$tBasic' },
        sOT: { $sum: '$tOT' },
        sAllow: { $sum: '$tAllow' },
        sOAllow: { $sum: '$tOAllow' },
        sPesangon: { $sum: '$tPesangon' },
        sThr: { $sum: '$tThr' },
        sOIncome: { $sum: '$tOIncome' },
        sAbsent: { $sum: '$tAbsent' },
        sODeduction: { $sum: '$tODeduction' },
        sICo: { $sum: '$tICo' },
        sIEmp: { $sum: '$tIEmp' },
        sTax: { $sum: '$tTax' },
      },
    },
  ]);

  return p[0];
};

module.exports = {
  sumBasic,
  sumOT,
  sumAllow,
  sumOAllow,
  sumPesangon,
  sumThr,
  sumOIncome,
  sumAbsent,
  sumODeduction,
  sumICo,
  sumIEmp,
  sumTax,
  sumAll,
};
