const {
  GraphQLObjectType,
  GraphQLList,
  GraphQLString,
  GraphQLFloat,
} = require('graphql');

const { DateFormat } = require('../scalar/date');

const EmpSummaryType = new GraphQLObjectType({
  name: 'EmpSummaryType',
  fields: () => ({
    _id: { type: GraphQLString },
    d0: { type: GraphQLString },
    e0: { type: GraphQLString },
    i0: { type: DateFormat },
    u0: { type: GraphQLString },
    y0: { type: GraphQLString },
    jan: { type: GraphQLFloat },
    feb: { type: GraphQLFloat },
    mar: { type: GraphQLFloat },
    apr: { type: GraphQLFloat },
    mei: { type: GraphQLFloat },
    jun: { type: GraphQLFloat },
    jul: { type: GraphQLFloat },
    agu: { type: GraphQLFloat },
    sep: { type: GraphQLFloat },
    okt: { type: GraphQLFloat },
    nov: { type: GraphQLFloat },
    des: { type: GraphQLFloat },
    jan1: { type: GraphQLFloat },
    feb1: { type: GraphQLFloat },
    mar1: { type: GraphQLFloat },
    apr1: { type: GraphQLFloat },
    mei1: { type: GraphQLFloat },
    jun1: { type: GraphQLFloat },
    jul1: { type: GraphQLFloat },
    agu1: { type: GraphQLFloat },
    sep1: { type: GraphQLFloat },
    okt1: { type: GraphQLFloat },
    nov1: { type: GraphQLFloat },
    des1: { type: GraphQLFloat },
    jan2: { type: GraphQLFloat },
    feb2: { type: GraphQLFloat },
    mar2: { type: GraphQLFloat },
    apr2: { type: GraphQLFloat },
    mei2: { type: GraphQLFloat },
    jun2: { type: GraphQLFloat },
    jul2: { type: GraphQLFloat },
    agu2: { type: GraphQLFloat },
    sep2: { type: GraphQLFloat },
    okt2: { type: GraphQLFloat },
    nov2: { type: GraphQLFloat },
    des2: { type: GraphQLFloat },
    tBasic: { type: GraphQLFloat },
    tOT: { type: GraphQLFloat },
    tAllow: { type: GraphQLFloat },
    tOAllow: { type: GraphQLFloat },
    tPesangon: { type: GraphQLFloat },
    tThr: { type: GraphQLFloat },
    tOIncome: { type: GraphQLFloat },
    tAbsent: { type: GraphQLFloat },
    tODeduction: { type: GraphQLFloat },
    tICo: { type: GraphQLFloat },
    tIEmp: { type: GraphQLFloat },
    tTax: { type: GraphQLFloat },
  }),
});

const SummaryType = new GraphQLObjectType({
  name: 'SummaryType',
  fields: () => ({
    _id: { type: GraphQLString },
    employee: { type: new GraphQLList(EmpSummaryType) },
  }),
});

module.exports = { SummaryType };
