export default {
  data() {
    return {
      department: [
        'Building Infrastructure & Service',
        'E-NNOVATION',
        'Electronic',
        'Finance & Administration',
        'General Affair & Human Resource',
        'HVAC-ELECTRICAL',
        'IRM Office Jakarta',
        'Information Technology',
        'MGT & Secretarial',
        'Management',
        'Marketing Euro & Africa',
        'Material Requirement Planning',
        'Mechanical Production',
        'Product Development & Control',
        'Production Division',
        'QUALITY ASSURANCE',
        'R&D DAQ & Control',
        'R&D Electronic',
        'R&D HVAC/Electrical',
        'R&D Mechanical',
        'R&D Software & Product Development',
        'Sales Marketing & Support',
        'Virtual Learning',
      ],
      section: [
        'Admin',
        'All Section',
        'Bidding',
        'Building/Infrastructure Service',
        'Carpentry',
        'Contract & Delivery Preparation',
        'Customer Service & Instalation, Training Support',
        'E-Nnovation',
        'Electronic',
        'Fabrication',
        'Factory Logistic',
        'Factory Manager',
        'General Accounting',
        'General Affair',
        'HVAC-Electrical',
        'HVAC/Electrical',
        'ISO Team',
        'IT Database Development',
        'IT Infrastructure & Maintenance',
        'Jakarta Office',
        'MRP – Administration',
        'MRP – BOM',
        'MRP – Purchasing',
        'MRP – Warehouse',
        'Machining & Tool Room',
        'Maintenance',
        'Management',
        'Marketing Service',
        'Material Support',
        'Mechanic',
        'Mechanical Assembly Administration',
        'Media',
        'Modeller',
        'Office  Boy',
        'PCB/Printing',
        'Painting',
        'Payroll Controller',
        'Personnel',
        'Personnel-OB',
        'President Director',
        'Production Administration',
        'Programming',
        'Quality Control',
        'R&D Administration',
        'R&D DAQ & Control',
        'R&D Electronic',
        'R&D HVAC/Electrical',
        'R&D Mechanical',
        'R&D Software & Product Development',
        'Receptionist',
        'Safety',
        'Security',
      ],
    };
  },
};
