export default {
  data() {
    return {
      department: [
        'Building Infrastructure & Service',
        'E-NNOVATION',
        'Electronic',
        'Finance & Administration',
        'Human Resource & General Affair',
        'HVAC-ELECTRICAL',
        'IRM Office Jakarta',
        'Information Technology',
        'MGT & Secretarial',
        'Management',
        'Marketing Euro & Africa',
        'Material Requirement Planning',
        'Mechanical Production',
        'Product Development & Control',
        'Production Division',
        'Quality Assurance',
        'R&D DAQ & Control',
        'R&D Electronic',
        'R&D HVAC/Electrical',
        'R&D Mechanical',
        'R&D Software & Product Development',
        'Sales Marketing & Support',
        'Virtual Learning',
      ],
      section: [
        'Admin',
        'All Section',
        'Bidding',
        'Building/Infrastructure Service',
        'Carpentry',
        'Contract & Delivery Preparation',
        'Customer Service & Instalation, Training Support',
        'E-Nnovation',
        'Electronic',
        'Fabrication',
        'Factory Logistic',
        'Factory Manager',
        'General Accounting',
        'General Affair',
        'HVAC-Electrical',
        'HVAC/Electrical',
        'ISO Team',
        'IT Database Development',
        'IT Infrastructure & Maintenance',
        'Jakarta Office',
        'MRP – Administration',
        'MRP – BOM',
        'MRP – Purchasing',
        'MRP – Warehouse',
        'Machining & Tool Room',
        'Maintenance',
        'Management',
        'Marketing Service',
        'Material Support',
        'Mechanic',
        'Mechanical Assembly Administration',
        'Media',
        'Modeller',
        'Office  Boy',
        'PCB/Printing',
        'Painting',
        'Payroll Controller',
        'Personnel',
        'Personnel-OB',
        'President Director',
        'Production Administration',
        'Programming',
        'Quality Control',
        'R&D Administration',
        'R&D DAQ & Control',
        'R&D Electronic',
        'R&D HVAC/Electrical',
        'R&D Mechanical',
        'R&D Software & Product Development',
        'Receptionist',
        'Safety',
        'Security',
      ],
      sectionCode: [
        '',
        '101',
        '110',
        '111',
        '113',
        '120',
        '121',
        '122',
        '129',
        '130',
        '131',
        '132',
        '133',
        '134',
        '135',
        '136',
        '139',
        '140',
        '142',
        '143',
        '150',
        '151',
        '152',
        '153',
        '154',
        '159',
        '161',
        '164',
        '170',
        '171',
        '179',
        '210',
        '211',
        '212',
        '213',
        '219',
        '220',
        '221',
        '229',
        '321',
        '322',
        '323',
        '324',
        '330',
        '331',
        '401',
        '402',
        '403',
        '510',
        '511',
        '513',
        '516',
        '521',
        '551',
        '561',
        '562',
      ],
      grade: [
        '',
        '1.11',
        '1.21',
        '1.22',
        '1.23',
        '2.11',
        '2.21',
        '2.22',
        '3.11',
        '3.13',
        '3.21',
        '3.22',
        '3.23',
        '4.11',
        '4.12',
        '4.13',
        '4.21',
        '4.23',
        '5.11',
        '5.12',
        '5.13',
        '5.21',
        '5.23',
        '6.11',
        '6.12',
        '6.21',
        '7.11',
        '7.12',
        '7.21',
        '8.12',
        '8.21',
        '9.11',
        '9.12',
        '9.21',
        '10.11',
        '10.21',
        '11.11',
        '11.21',
        '12.21',
        '13.11',
        '14.11',
        '14.21',
      ],
      jabatan: [
        'ACT. JR MANAGER',
        'ACT. SUPERVISOR',
        'ACT. ENGINEER 2',
        'ACT. SUPERVISOR',
        'ACT. TECHNICIAN 1',
        'ASS. ENGINEER',
        'CLERK',
        'DIRECTOR',
        'ENGINEER',
        'ENGINEER 1',
        'ENGINEER 2',
        'ENGINEER 3',
        'ENGINEER 4',
        'ENGINEER 5',
        'GADA PRATAMA 2',
        'GADA PRATAMA 3',
        'GADA PRATAMA 4',
        'GADA PRATAMA 5',
        'GADA PRATAMA 6',
        'INSPECTOR 3',
        'JR. OFFICER',
        'JR. SUPERVISOR',
        'JR. CLERK',
        'MANAGER 1',
        'MANAGER 2',
        'OFFICE BOY 1',
        'OFFICE BOY 3',
        'OFFICER',
        'PLT. MANAGER',
        'PRESIDENT DIRECTOR',
        'SR. CLERK',
        'SR. ENGINEER 1',
        'SR. ENGINEER 2',
        'SR. ENGINEER 3',
        'SR. OFFICER',
        'SR. SUPERVISOR',
        'SR. SUPERVISOR 3',
        'SR. TECHNICIAN 2',
        'SR. TECHNICIAN 3',
        'SR. TECHNICIAN 4',
        'SR. TECHNICIAN 5',
        'SR. MANAGER 2',
        'SR. MANAGER 3',
        'SUPERVISOR',
        'TECHNICIAN 1',
        'TECHNICIAN 2',
        'TECHNICIAN 3',
      ],
    };
  },
};
