export default {
  data() {
    return {
      department: [
        'Building Infrastructure & Service',
        'Electronic',
        'Finance & Administration',
        'HVAC/Electrical',
        'Human Resource & General Affair',
        'IRM Office Jakarta',
        'Information Technology',
        'MGT & Secretarial',
        'Management',
        'Marketing Euro & Africa',
        'Material Requirement Planning',
        'Mechanical Production',
        'Product Development & Control',
        'Production Division',
        'Quality Assturance',
        'R&D DAQ & Control',
        'R&D Electronic',
        'R&D HVAC/Electrical',
        'R&D Mechanical',
        'R&D Software & Product Development',
        'Sales Marketing & Support',
        'Virtual Learning & Ennovation',
      ],
      section: [
        'Admin',
        'All Section',
        'Bidding',
        'Building/Infrastructure Service',
        'Carpentry',
        'Contract & Delivery Preparation',
        'Customer Service & Instalation, Training Support',
        'Electronic',
        'Ennovation',
        'Fabrication',
        'Factory Logistic',
        'Factory Manager',
        'General Accounting',
        'General Affair',
        'HVAC/Electrical',
        'ISO Team',
        'IT Database Development',
        'IT Infrastructure & Maintenance',
        'Jakarta Office',
        'MRP/Administration',
        'MRP/BOM',
        'MRP/Purchasing',
        'MRP/Warehouse',
        'Machining & Tool Room',
        'Maintenance',
        'Management',
        'Marketing Service',
        'Material Support',
        'Mechanic',
        'Mechanical Asstembly Administration',
        'Media',
        'Modeller',
        'PCB/Printing',
        'Painting',
        'Payroll Controller',
        'Personnel',
        'President Director',
        'Production Administration',
        'Programming',
        'Quality Control',
        'R&D Administration',
        'R&D DAQ & Control',
        'R&D Electronic',
        'R&D HVAC/Electrical',
        'R&D Mechanical',
        'R&D Software & Product Development',
        'Receptionist',
        'Safety',
        'Security',
      ],
      sectionCode: [
        '',
        '101',
        '110',
        '111',
        '113',
        '120',
        '121',
        '122',
        '129',
        '130',
        '131',
        '132',
        '133',
        '134',
        '135',
        '136',
        '139',
        '140',
        '142',
        '143',
        '150',
        '151',
        '152',
        '153',
        '154',
        '159',
        '161',
        '164',
        '170',
        '171',
        '179',
        '210',
        '211',
        '212',
        '213',
        '219',
        '220',
        '221',
        '229',
        '321',
        '322',
        '323',
        '324',
        '330',
        '331',
        '401',
        '402',
        '403',
        '510',
        '511',
        '513',
        '516',
        '521',
        '551',
        '561',
        '562',
      ],
      grade: [
        '',
        '1.11',
        '1.21',
        '1.22',
        '1.23',
        '2.11',
        '2.21',
        '2.22',
        '3.11',
        '3.13',
        '3.21',
        '3.22',
        '3.23',
        '4.11',
        '4.12',
        '4.13',
        '4.21',
        '4.23',
        '5.11',
        '5.12',
        '5.13',
        '5.21',
        '5.23',
        '6.11',
        '6.12',
        '6.21',
        '7.11',
        '7.12',
        '7.21',
        '8.12',
        '8.21',
        '9.11',
        '9.12',
        '9.21',
        '10.11',
        '10.21',
        '11.11',
        '11.21',
        '12.21',
        '13.11',
        '14.11',
        '14.21',
      ],
      jabatan: [
        'Act. Engineer 2',
        'Act. Jr. Manager',
        'Act. Supervisor',
        'Act. Technician 1',
        'Asst. Engineer',
        'Clerk',
        'Director',
        'Engineer 1',
        'Engineer 2',
        'Engineer 3',
        'Engineer 4',
        'Engineer 5',
        'Gada Pratama 2',
        'Gada Pratama 3',
        'Gada Pratama 4',
        'Gada Pratama 5',
        'Gada Pratama 6',
        'Inspector 3',
        'Jr. Clerk',
        'Jr. Officer',
        'Jr. Supervisor',
        'Manager 1',
        'Manager 2',
        'Office Boy 1',
        'Office Boy 3',
        'Officer',
        'Plt. Manager',
        'President Director',
        'Sr. Clerk',
        'Sr. Engineer 1',
        'Sr. Engineer 2',
        'Sr. Engineer 3',
        'Sr. Manager 2',
        'Sr. Manager 3',
        'Sr. Officer',
        'Sr. Supervisor',
        'Sr. Supervisor 3',
        'Sr. Technician 2',
        'Sr. Technician 3',
        'Sr. Technician 4',
        'Sr. Technician 5',
        'Supervisor',
        'Technician 1',
        'Technician 2',
        'Technician 3',
      ],
    };
  },
};
