const {
  GraphQLObjectType,
  GraphQLList,
  GraphQLString,
  GraphQLInt,
  GraphQLFloat,
} = require('graphql');

const { DateFormat } = require('../scalar/date');
const { IntPre0, FloatPre2, FloatPre4 } = require('../scalar/number');

const EmployeeType = new GraphQLObjectType({
  name: 'EmployeeType',
  fields: () => ({
    _id: { type: GraphQLString },
    d0: { type: GraphQLString },
    e0: { type: GraphQLString },
    g0: { type: GraphQLInt },
    h0: { type: GraphQLString },
    i0: { type: DateFormat },
    j0: { type: GraphQLInt },
    k0: { type: DateFormat },
    l0: { type: IntPre0 },
    m0: { type: GraphQLString },
    n0: { type: GraphQLString },
    o0: { type: DateFormat },
    p0: { type: GraphQLString },
    q0: { type: GraphQLString },
    r0: { type: GraphQLString },
    s0: { type: GraphQLString },
    t0: { type: GraphQLString },
    u0: { type: GraphQLString },
    v0: { type: GraphQLString },
    w0: { type: GraphQLString },
    x0: { type: GraphQLString },
    y0: { type: GraphQLString },
    z0: { type: GraphQLString },
    aa0: { type: GraphQLString },
    ab0: { type: GraphQLFloat },
    ac0: { type: GraphQLFloat },
    ad0: { type: GraphQLFloat },
    ae0: { type: GraphQLFloat },
    af0: { type: GraphQLFloat },
    ag0: { type: GraphQLFloat },
    ah0: { type: GraphQLFloat },
    ai0: { type: GraphQLFloat },
    aj0: { type: GraphQLFloat },
    ak0: { type: GraphQLFloat },
    al0: { type: GraphQLFloat },
    am0: { type: GraphQLFloat },
    an0: { type: GraphQLFloat },
    ao0: { type: GraphQLFloat },
    ap0: { type: GraphQLFloat },
    aq0: { type: GraphQLFloat },
    ar0: { type: GraphQLFloat },
    as0: { type: GraphQLFloat },
    at0: { type: GraphQLFloat },
    au0: { type: GraphQLFloat },
    av0: { type: GraphQLFloat },
    aw0: { type: GraphQLFloat },
    ax0: { type: IntPre0 },
    ba0: { type: GraphQLFloat },
    bb0: { type: GraphQLFloat },
    bc0: { type: GraphQLFloat },
    bd0: { type: GraphQLFloat },
    be0: { type: GraphQLFloat },
    bf0: { type: GraphQLFloat },
    bg0: { type: GraphQLFloat },
    bh0: { type: GraphQLFloat },
    bi0: { type: GraphQLFloat },
    bj0: { type: GraphQLFloat },
    bl0: { type: GraphQLFloat },
    bm0: { type: GraphQLFloat },
    bn0: { type: GraphQLFloat },
    bo0: { type: GraphQLFloat },
    bp0: { type: GraphQLFloat },
    bq0: { type: GraphQLFloat },
    br0: { type: GraphQLFloat },
    bs0: { type: GraphQLFloat },
    bt0: { type: GraphQLFloat },
    bu0: { type: GraphQLFloat },
    bv0: { type: GraphQLFloat },
    bw0: { type: GraphQLFloat },
    bx0: { type: GraphQLFloat },
    by0: { type: GraphQLFloat },
    bz0: { type: GraphQLFloat },
    ca0: { type: IntPre0 },
    cb0: { type: IntPre0 },
    cc0: { type: IntPre0 },
    cd0: { type: IntPre0 },
    ce0: { type: IntPre0 },
    ci0: { type: IntPre0 },
    cj0: { type: IntPre0 },
    cq0: { type: IntPre0 },
    cr0: { type: IntPre0 },
    cw0: { type: GraphQLFloat },
    cx0: { type: GraphQLFloat },
    cz0: { type: IntPre0 },
    da0: { type: IntPre0 },
    db0: { type: IntPre0 },
    dc0: { type: IntPre0 },
    dd0: { type: IntPre0 },
    de0: { type: IntPre0 },
    dg0: { type: IntPre0 },
    dh0: { type: IntPre0 },
    di0: { type: IntPre0 },
    dj0: { type: IntPre0 },
    dk0: { type: IntPre0 },
    dl0: { type: IntPre0 },
    dm0: { type: IntPre0 },
    dn0: { type: IntPre0 },
    do0: { type: IntPre0 },
    dp0: { type: IntPre0 },
    dr0: { type: GraphQLFloat },
    ds0: { type: GraphQLFloat },
    dt0: { type: GraphQLFloat },
    du0: { type: GraphQLFloat },
    dv0: { type: GraphQLFloat },
    dw0: { type: GraphQLFloat },
    dx0: { type: GraphQLFloat },
    dy0: { type: GraphQLFloat },
    eb0: { type: IntPre0 },
    ec0: { type: IntPre0 },
    ed0: { type: IntPre0 },
    ex0: { type: GraphQLInt },
  }),
});

const TotalType = new GraphQLObjectType({
  name: 'TotalType',
  fields: () => ({
    sab0: { type: IntPre0 },
    sac0: { type: IntPre0 },
    sad0: { type: IntPre0 },
    sae0: { type: IntPre0 },
    saf0: { type: IntPre0 },
    sag0: { type: IntPre0 },
    sah0: { type: IntPre0 },
    sai0: { type: IntPre0 },
    saj0: { type: IntPre0 },
    sak0: { type: IntPre0 },
    sal0: { type: IntPre0 },
    sam0: { type: IntPre0 },
    san0: { type: IntPre0 },
    sao0: { type: IntPre0 },
    sap0: { type: IntPre0 },
    saq0: { type: IntPre0 },
    sar0: { type: IntPre0 },
    sas0: { type: IntPre0 },
    sat0: { type: IntPre0 },
    sau0: { type: IntPre0 },
    sav0: { type: IntPre0 },
    saw0: { type: IntPre0 },
    sba0: { type: IntPre0 },
    sbb0: { type: IntPre0 },
    sbc0: { type: IntPre0 },
    sbd0: { type: IntPre0 },
    sbe0: { type: IntPre0 },
    sbf0: { type: IntPre0 },
    sbg0: { type: IntPre0 },
    sbh0: { type: IntPre0 },
    sbi0: { type: IntPre0 },
    sbj0: { type: IntPre0 },
    sbl0: { type: IntPre0 },
    sbm0: { type: IntPre0 },
    sbn0: { type: IntPre0 },
    sbo0: { type: IntPre0 },
    sbp0: { type: IntPre0 },
    sbq0: { type: IntPre0 },
    sbr0: { type: IntPre0 },
    sbs0: { type: IntPre0 },
    sbt0: { type: IntPre0 },
    sbu0: { type: IntPre0 },
    sbv0: { type: IntPre0 },
    sbw0: { type: IntPre0 },
    sbx0: { type: IntPre0 },
    sby0: { type: FloatPre2 },
    sbz0: { type: IntPre0 },
    sca0: { type: IntPre0 },
    scb0: { type: IntPre0 },
    scc0: { type: IntPre0 },
    scd0: { type: IntPre0 },
    sce0: { type: IntPre0 },
    sci0: { type: IntPre0 },
    scj0: { type: IntPre0 },
    scq0: { type: IntPre0 },
    scr0: { type: IntPre0 },
    scw0: { type: IntPre0 },
    scx0: { type: IntPre0 },
    scz0: { type: IntPre0 },
    sda0: { type: IntPre0 },
    sdb0: { type: IntPre0 },
    sdc0: { type: IntPre0 },
    sdd0: { type: IntPre0 },
    sde0: { type: IntPre0 },
    sdg0: { type: IntPre0 },
    sdh0: { type: IntPre0 },
    sdi0: { type: IntPre0 },
    sdj0: { type: IntPre0 },
    sdk0: { type: IntPre0 },
    sdl0: { type: IntPre0 },
    sdm0: { type: IntPre0 },
    sdn0: { type: IntPre0 },
    sdo0: { type: IntPre0 },
    sdp0: { type: IntPre0 },
    sdr0: { type: IntPre0 },
    sds0: { type: IntPre0 },
    sdt0: { type: IntPre0 },
    sdu0: { type: IntPre0 },
    sdv0: { type: IntPre0 },
    sdw0: { type: IntPre0 },
    sdx0: { type: IntPre0 },
    sdy0: { type: IntPre0 },
    seb0: { type: IntPre0 },
    sec0: { type: IntPre0 },
    sed0: { type: IntPre0 },
  }),
});

const PayrollType = new GraphQLObjectType({
  name: 'PayrollType',
  fields: () => ({
    _id: { type: GraphQLString },
    from: { type: GraphQLString },
    to: { type: GraphQLString },
    year: { type: GraphQLInt },
    period: { type: GraphQLString },
    employee: { type: new GraphQLList(EmployeeType) },
    total: { type: TotalType },
  }),
});

module.exports = { PayrollType };
