const {
  GraphQLObjectType,
  GraphQLList,
  GraphQLString,
  GraphQLInt,
} = require('graphql');

const { DateFormat } = require('../scalar/date');
const { IntPre0, FloatPre2 } = require('../scalar/number');

const EmployeeType = new GraphQLObjectType({
  name: 'EmployeeType',
  fields: () => ({
    _id: { type: GraphQLString },
    d0: { type: GraphQLString },
    e0: { type: GraphQLString },
    g0: { type: GraphQLInt },
    h0: { type: GraphQLString },
    i0: { type: DateFormat },
    j0: { type: GraphQLInt },
    k0: { type: DateFormat },
    l0: { type: IntPre0 },
    m0: { type: GraphQLString },
    n0: { type: GraphQLString },
    o0: { type: DateFormat },
    p0: { type: GraphQLString },
    q0: { type: GraphQLString },
    r0: { type: GraphQLString },
    s0: { type: GraphQLString },
    t0: { type: GraphQLString },
    u0: { type: GraphQLString },
    v0: { type: GraphQLString },
    w0: { type: GraphQLString },
    x0: { type: GraphQLString },
    y0: { type: GraphQLString },
    z0: { type: GraphQLString },
    aa0: { type: GraphQLString },
    ab0: { type: FloatPre2 },
    ac0: { type: IntPre0 },
    ad0: { type: FloatPre2 },
    ae0: { type: IntPre0 },
    af0: { type: FloatPre2 },
    ag0: { type: IntPre0 },
    ah0: { type: IntPre0 },
    ai0: { type: IntPre0 },
    aj0: { type: IntPre0 },
    ak0: { type: IntPre0 },
    al0: { type: IntPre0 },
    am0: { type: IntPre0 },
    an0: { type: IntPre0 },
    ao0: { type: IntPre0 },
    ap0: { type: IntPre0 },
    aq0: { type: IntPre0 },
    ar0: { type: IntPre0 },
    as0: { type: IntPre0 },
    at0: { type: IntPre0 },
    au0: { type: IntPre0 },
    av0: { type: IntPre0 },
    aw0: { type: IntPre0 },
    ax0: { type: IntPre0 },
    ba0: { type: IntPre0 },
    bb0: { type: IntPre0 },
    bc0: { type: IntPre0 },
    bd0: { type: IntPre0 },
    be0: { type: IntPre0 },
    bf0: { type: IntPre0 },
    bg0: { type: IntPre0 },
    bh0: { type: IntPre0 },
    bi0: { type: IntPre0 },
    bj0: { type: IntPre0 },
  }),
});

const TotalType = new GraphQLObjectType({
  name: 'TotalType',
  fields: () => ({
    sab0: { type: IntPre0 },
    sac0: { type: IntPre0 },
    sad0: { type: IntPre0 },
    sae0: { type: IntPre0 },
    saf0: { type: IntPre0 },
    sag0: { type: IntPre0 },
    sah0: { type: IntPre0 },
    sai0: { type: IntPre0 },
    saj0: { type: IntPre0 },
    sak0: { type: IntPre0 },
    sal0: { type: IntPre0 },
    sam0: { type: IntPre0 },
    san0: { type: IntPre0 },
    sao0: { type: IntPre0 },
    sap0: { type: IntPre0 },
    saq0: { type: IntPre0 },
    sar0: { type: IntPre0 },
    sas0: { type: IntPre0 },
    sat0: { type: IntPre0 },
    sau0: { type: IntPre0 },
    sav0: { type: IntPre0 },
    saw0: { type: IntPre0 },
    sba0: { type: IntPre0 },
    sbb0: { type: IntPre0 },
    sbc0: { type: IntPre0 },
    sbd0: { type: IntPre0 },
    sbe0: { type: IntPre0 },
    sbf0: { type: IntPre0 },
    sbg0: { type: IntPre0 },
    sbh0: { type: IntPre0 },
    sbi0: { type: IntPre0 },
    sbj0: { type: IntPre0 },
  }),
});

const PayrollType = new GraphQLObjectType({
  name: 'PayrollType',
  fields: () => ({
    _id: { type: GraphQLString },
    from: { type: GraphQLString },
    to: { type: GraphQLString },
    year: { type: GraphQLInt },
    period: { type: GraphQLString },
    employee: { type: new GraphQLList(EmployeeType) },
    total: { type: TotalType },
  }),
});

module.exports = { PayrollType };
